var headerResultTemplate = '<h1><a href="index.html">Mrs. Kravitz</a>' +
'	' +
'</h1>' +
'<form id="search"><input type="text" value="" id="header_search_box" class="searcher"/><input type="submit" value="Search" class="btn" /></form>' + 
'<ul class="right_menu">' +
'	<li>built by <a href="http://www.twitter.com/steveodom">@steveodom</a>' +
'</li>' +
'	<li style="width=137px;"><a href="">data sources <b></b></a><div id="data_sources" class="dropdown"><p>Each page is generated by doing close to 40 calls to various API\'s. The two most important ones of which are from <a href="http://infochimps.com">Infochimps</a> and <a href="http://linkedin.com">Linkedin</a>.</p>'+
' <p>Calls to Infochimps\' <a href="http://api.infochimps.com/describe/soc/net/tw/strong_links">strong links</a> api generates the friend graph and a call to the <a href="http://www.infochimps.com/datasets/qwerly-profile-search">qwerly data</a> generates the social networks.</p><p>Linkedin generates all the job-related information.</p><p>There are various calls to <a href="http://klout.com">Klout</a> (for the Klout score and the topics), Flickr, Lastfm, and <a href="http://developer.yahoo.com/geo/placefinder/">Yahoo\'s PlaceFinder</a> service (to normalize locations).</p><p>Oh, and of course, Twitter.</p> </div></li>' +
'</ul>'